//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryInatechMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CustomerTb
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "This Field is mandatory")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This Field is mandatory")]
        public int Age { get; set; }
        [Required(ErrorMessage = "This Field is mandatory")]
        public string Address { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage ="This Field is mandatory")]
        public string Password { get; set; }

        [Required(ErrorMessage = "This Field is mandatory")]
        public string Email { get; set; }
    }
}
